package org.louis.hometutor.po;

import java.util.Date;

public class AccessTokenLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_token_log.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_token_log.key
     *
     * @mbggenerated
     */
    private String key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_token_log.accessToken
     *
     * @mbggenerated
     */
    private String accessToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_token_log.createTimeStamp
     *
     * @mbggenerated
     */
    private Date createTimeStamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_token_log
     *
     * @mbggenerated
     */
    public AccessTokenLog(Long id, String key, String accessToken, Date createTimeStamp) {
        this.id = id;
        this.key = key;
        this.accessToken = accessToken;
        this.createTimeStamp = createTimeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_token_log.id
     *
     * @return the value of access_token_log.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_token_log.key
     *
     * @return the value of access_token_log.key
     *
     * @mbggenerated
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_token_log.accessToken
     *
     * @return the value of access_token_log.accessToken
     *
     * @mbggenerated
     */
    public String getAccessToken() {
        return accessToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_token_log.createTimeStamp
     *
     * @return the value of access_token_log.createTimeStamp
     *
     * @mbggenerated
     */
    public Date getCreateTimeStamp() {
        return createTimeStamp;
    }
}