package org.louis.hometutor.po;

import java.util.Date;

public class Article {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.createTimeStamp
     *
     * @mbggenerated
     */
    private Date createTimeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.updateTimeStamp
     *
     * @mbggenerated
     */
    private Date updateTimeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.desc
     *
     * @mbggenerated
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.author
     *
     * @mbggenerated
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.thumbnailUrl
     *
     * @mbggenerated
     */
    private String thumbnailUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.ownerId
     *
     * @mbggenerated
     */
    private Long ownerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.creatorId
     *
     * @mbggenerated
     */
    private Long creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.updatorId
     *
     * @mbggenerated
     */
    private Long updatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.ownerType
     *
     * @mbggenerated
     */
    private Integer ownerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.creatorType
     *
     * @mbggenerated
     */
    private Integer creatorType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.updatorType
     *
     * @mbggenerated
     */
    private Integer updatorType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.likeCount
     *
     * @mbggenerated
     */
    private Integer likeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.commentCount
     *
     * @mbggenerated
     */
    private Integer commentCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.collectCount
     *
     * @mbggenerated
     */
    private Integer collectCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.resourceCount
     *
     * @mbggenerated
     */
    private Integer resourceCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.hasVideo
     *
     * @mbggenerated
     */
    private Boolean hasVideo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.hasAudio
     *
     * @mbggenerated
     */
    private Boolean hasAudio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.isShow
     *
     * @mbggenerated
     */
    private Boolean isShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.readCount
     *
     * @mbggenerated
     */
    private Integer readCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.publicTime
     *
     * @mbggenerated
     */
    private Date publicTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated
     */
    public Article(Long id, Date createTimeStamp, Date updateTimeStamp, Integer type, String desc, String author, String thumbnailUrl, String title, Long ownerId, Long creatorId, Long updatorId, Integer ownerType, Integer creatorType, Integer updatorType, Integer likeCount, Integer commentCount, Integer collectCount, Integer resourceCount, Boolean hasVideo, Boolean hasAudio, Boolean isShow, Integer readCount, Date publicTime, String content) {
        this.id = id;
        this.createTimeStamp = createTimeStamp;
        this.updateTimeStamp = updateTimeStamp;
        this.type = type;
        this.desc = desc;
        this.author = author;
        this.thumbnailUrl = thumbnailUrl;
        this.title = title;
        this.ownerId = ownerId;
        this.creatorId = creatorId;
        this.updatorId = updatorId;
        this.ownerType = ownerType;
        this.creatorType = creatorType;
        this.updatorType = updatorType;
        this.likeCount = likeCount;
        this.commentCount = commentCount;
        this.collectCount = collectCount;
        this.resourceCount = resourceCount;
        this.hasVideo = hasVideo;
        this.hasAudio = hasAudio;
        this.isShow = isShow;
        this.readCount = readCount;
        this.publicTime = publicTime;
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.id
     *
     * @return the value of article.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.createTimeStamp
     *
     * @return the value of article.createTimeStamp
     *
     * @mbggenerated
     */
    public Date getCreateTimeStamp() {
        return createTimeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.updateTimeStamp
     *
     * @return the value of article.updateTimeStamp
     *
     * @mbggenerated
     */
    public Date getUpdateTimeStamp() {
        return updateTimeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.type
     *
     * @return the value of article.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.desc
     *
     * @return the value of article.desc
     *
     * @mbggenerated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.author
     *
     * @return the value of article.author
     *
     * @mbggenerated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.thumbnailUrl
     *
     * @return the value of article.thumbnailUrl
     *
     * @mbggenerated
     */
    public String getThumbnailUrl() {
        return thumbnailUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.title
     *
     * @return the value of article.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.ownerId
     *
     * @return the value of article.ownerId
     *
     * @mbggenerated
     */
    public Long getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.creatorId
     *
     * @return the value of article.creatorId
     *
     * @mbggenerated
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.updatorId
     *
     * @return the value of article.updatorId
     *
     * @mbggenerated
     */
    public Long getUpdatorId() {
        return updatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.ownerType
     *
     * @return the value of article.ownerType
     *
     * @mbggenerated
     */
    public Integer getOwnerType() {
        return ownerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.creatorType
     *
     * @return the value of article.creatorType
     *
     * @mbggenerated
     */
    public Integer getCreatorType() {
        return creatorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.updatorType
     *
     * @return the value of article.updatorType
     *
     * @mbggenerated
     */
    public Integer getUpdatorType() {
        return updatorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.likeCount
     *
     * @return the value of article.likeCount
     *
     * @mbggenerated
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.commentCount
     *
     * @return the value of article.commentCount
     *
     * @mbggenerated
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.collectCount
     *
     * @return the value of article.collectCount
     *
     * @mbggenerated
     */
    public Integer getCollectCount() {
        return collectCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.resourceCount
     *
     * @return the value of article.resourceCount
     *
     * @mbggenerated
     */
    public Integer getResourceCount() {
        return resourceCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.hasVideo
     *
     * @return the value of article.hasVideo
     *
     * @mbggenerated
     */
    public Boolean getHasVideo() {
        return hasVideo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.hasAudio
     *
     * @return the value of article.hasAudio
     *
     * @mbggenerated
     */
    public Boolean getHasAudio() {
        return hasAudio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.isShow
     *
     * @return the value of article.isShow
     *
     * @mbggenerated
     */
    public Boolean getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.readCount
     *
     * @return the value of article.readCount
     *
     * @mbggenerated
     */
    public Integer getReadCount() {
        return readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.publicTime
     *
     * @return the value of article.publicTime
     *
     * @mbggenerated
     */
    public Date getPublicTime() {
        return publicTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.content
     *
     * @return the value of article.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }
}