package org.louis.hometutor.po;

import java.util.Date;

public class AuthorityVerifyResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority_verify_resource.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority_verify_resource.createTimeStamp
     *
     * @mbggenerated
     */
    private Date createTimeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority_verify_resource.updateTimeStamp
     *
     * @mbggenerated
     */
    private Date updateTimeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority_verify_resource.resourceUrl
     *
     * @mbggenerated
     */
    private String resourceUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority_verify_resource.authorityVerifyId
     *
     * @mbggenerated
     */
    private Long authorityVerifyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority_verify_resource
     *
     * @mbggenerated
     */
    public AuthorityVerifyResource(Long id, Date createTimeStamp, Date updateTimeStamp, String resourceUrl, Long authorityVerifyId) {
        this.id = id;
        this.createTimeStamp = createTimeStamp;
        this.updateTimeStamp = updateTimeStamp;
        this.resourceUrl = resourceUrl;
        this.authorityVerifyId = authorityVerifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority_verify_resource.id
     *
     * @return the value of authority_verify_resource.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority_verify_resource.createTimeStamp
     *
     * @return the value of authority_verify_resource.createTimeStamp
     *
     * @mbggenerated
     */
    public Date getCreateTimeStamp() {
        return createTimeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority_verify_resource.updateTimeStamp
     *
     * @return the value of authority_verify_resource.updateTimeStamp
     *
     * @mbggenerated
     */
    public Date getUpdateTimeStamp() {
        return updateTimeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority_verify_resource.resourceUrl
     *
     * @return the value of authority_verify_resource.resourceUrl
     *
     * @mbggenerated
     */
    public String getResourceUrl() {
        return resourceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority_verify_resource.authorityVerifyId
     *
     * @return the value of authority_verify_resource.authorityVerifyId
     *
     * @mbggenerated
     */
    public Long getAuthorityVerifyId() {
        return authorityVerifyId;
    }
}