package org.louis.hometutor.po;

import java.util.Date;

public class AuthorityVerify {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority_verify.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority_verify.createTimeStamp
     *
     * @mbggenerated
     */
    private Date createTimeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority_verify.updateTimeStamp
     *
     * @mbggenerated
     */
    private Date updateTimeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority_verify.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority_verify.verifyTimeStamp
     *
     * @mbggenerated
     */
    private Date verifyTimeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority_verify.doctorId
     *
     * @mbggenerated
     */
    private Long doctorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority_verify.resultDesc
     *
     * @mbggenerated
     */
    private String resultDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority_verify
     *
     * @mbggenerated
     */
    public AuthorityVerify(Long id, Date createTimeStamp, Date updateTimeStamp, Integer status, Date verifyTimeStamp, Long doctorId, String resultDesc) {
        this.id = id;
        this.createTimeStamp = createTimeStamp;
        this.updateTimeStamp = updateTimeStamp;
        this.status = status;
        this.verifyTimeStamp = verifyTimeStamp;
        this.doctorId = doctorId;
        this.resultDesc = resultDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority_verify.id
     *
     * @return the value of authority_verify.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority_verify.createTimeStamp
     *
     * @return the value of authority_verify.createTimeStamp
     *
     * @mbggenerated
     */
    public Date getCreateTimeStamp() {
        return createTimeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority_verify.updateTimeStamp
     *
     * @return the value of authority_verify.updateTimeStamp
     *
     * @mbggenerated
     */
    public Date getUpdateTimeStamp() {
        return updateTimeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority_verify.status
     *
     * @return the value of authority_verify.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority_verify.verifyTimeStamp
     *
     * @return the value of authority_verify.verifyTimeStamp
     *
     * @mbggenerated
     */
    public Date getVerifyTimeStamp() {
        return verifyTimeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority_verify.doctorId
     *
     * @return the value of authority_verify.doctorId
     *
     * @mbggenerated
     */
    public Long getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority_verify.resultDesc
     *
     * @return the value of authority_verify.resultDesc
     *
     * @mbggenerated
     */
    public String getResultDesc() {
        return resultDesc;
    }
}