package org.louis.hometutor.po;

import java.util.Date;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.createTimeStamp
     *
     * @mbggenerated
     */
    private Date createTimeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.updateTimeStamp
     *
     * @mbggenerated
     */
    private Date updateTimeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.posterId
     *
     * @mbggenerated
     */
    private Long posterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.posterType
     *
     * @mbggenerated
     */
    private Integer posterType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.replyTargetId
     *
     * @mbggenerated
     */
    private Long replyTargetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.replyTargetType
     *
     * @mbggenerated
     */
    private Integer replyTargetType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commentTargetId
     *
     * @mbggenerated
     */
    private Long commentTargetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commentTargetType
     *
     * @mbggenerated
     */
    private Integer commentTargetType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    public Comment(Long id, Date createTimeStamp, Date updateTimeStamp, Long posterId, Integer posterType, Long replyTargetId, Integer replyTargetType, Long commentTargetId, Integer commentTargetType, String content) {
        this.id = id;
        this.createTimeStamp = createTimeStamp;
        this.updateTimeStamp = updateTimeStamp;
        this.posterId = posterId;
        this.posterType = posterType;
        this.replyTargetId = replyTargetId;
        this.replyTargetType = replyTargetType;
        this.commentTargetId = commentTargetId;
        this.commentTargetType = commentTargetType;
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.createTimeStamp
     *
     * @return the value of comment.createTimeStamp
     *
     * @mbggenerated
     */
    public Date getCreateTimeStamp() {
        return createTimeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.updateTimeStamp
     *
     * @return the value of comment.updateTimeStamp
     *
     * @mbggenerated
     */
    public Date getUpdateTimeStamp() {
        return updateTimeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.posterId
     *
     * @return the value of comment.posterId
     *
     * @mbggenerated
     */
    public Long getPosterId() {
        return posterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.posterType
     *
     * @return the value of comment.posterType
     *
     * @mbggenerated
     */
    public Integer getPosterType() {
        return posterType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.replyTargetId
     *
     * @return the value of comment.replyTargetId
     *
     * @mbggenerated
     */
    public Long getReplyTargetId() {
        return replyTargetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.replyTargetType
     *
     * @return the value of comment.replyTargetType
     *
     * @mbggenerated
     */
    public Integer getReplyTargetType() {
        return replyTargetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commentTargetId
     *
     * @return the value of comment.commentTargetId
     *
     * @mbggenerated
     */
    public Long getCommentTargetId() {
        return commentTargetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commentTargetType
     *
     * @return the value of comment.commentTargetType
     *
     * @mbggenerated
     */
    public Integer getCommentTargetType() {
        return commentTargetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.content
     *
     * @return the value of comment.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }
}