package org.louis.hometutor.po;

import java.util.Date;

public class CustomTagTemplate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom_tag_template.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom_tag_template.createTimeStamp
     *
     * @mbggenerated
     */
    private Date createTimeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom_tag_template.updateTimeStamp
     *
     * @mbggenerated
     */
    private Date updateTimeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom_tag_template.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom_tag_template.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom_tag_template.ownerId
     *
     * @mbggenerated
     */
    private Long ownerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom_tag_template.ownerType
     *
     * @mbggenerated
     */
    private Integer ownerType;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_tag_template
     *
     * @mbggenerated
     */
    public CustomTagTemplate(Long id, Date createTimeStamp, Date updateTimeStamp, String name, Integer type, Long ownerId, Integer ownerType) {
        this.id = id;
        this.createTimeStamp = createTimeStamp;
        this.updateTimeStamp = updateTimeStamp;
        this.name = name;
        this.type = type;
        this.ownerId = ownerId;
        this.ownerType = ownerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom_tag_template.id
     *
     * @return the value of custom_tag_template.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom_tag_template.createTimeStamp
     *
     * @return the value of custom_tag_template.createTimeStamp
     *
     * @mbggenerated
     */
    public Date getCreateTimeStamp() {
        return createTimeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom_tag_template.updateTimeStamp
     *
     * @return the value of custom_tag_template.updateTimeStamp
     *
     * @mbggenerated
     */
    public Date getUpdateTimeStamp() {
        return updateTimeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom_tag_template.name
     *
     * @return the value of custom_tag_template.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom_tag_template.type
     *
     * @return the value of custom_tag_template.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom_tag_template.ownerId
     *
     * @return the value of custom_tag_template.ownerId
     *
     * @mbggenerated
     */
    public Long getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom_tag_template.ownerType
     *
     * @return the value of custom_tag_template.ownerType
     *
     * @mbggenerated
     */
    public Integer getOwnerType() {
        return ownerType;
    }
}