package org.louis.hometutor.po;

import java.util.Date;

public class EnumItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enum_item.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enum_item.createTimeStamp
     *
     * @mbggenerated
     */
    private Date createTimeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enum_item.updateTimeStamp
     *
     * @mbggenerated
     */
    private Date updateTimeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enum_item.creatorName
     *
     * @mbggenerated
     */
    private String creatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enum_item.updatorId
     *
     * @mbggenerated
     */
    private Long updatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enum_item.updatorName
     *
     * @mbggenerated
     */
    private String updatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enum_item.enumId
     *
     * @mbggenerated
     */
    private Long enumId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enum_item.key
     *
     * @mbggenerated
     */
    private String key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enum_item.value
     *
     * @mbggenerated
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enum_item.creatorId
     *
     * @mbggenerated
     */
    private Long creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enum_item.text
     *
     * @mbggenerated
     */
    private String text;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enum_item
     *
     * @mbggenerated
     */
    public EnumItem(Long id, Date createTimeStamp, Date updateTimeStamp, String creatorName, Long updatorId, String updatorName, Long enumId, String key, String value, Long creatorId, String text) {
        this.id = id;
        this.createTimeStamp = createTimeStamp;
        this.updateTimeStamp = updateTimeStamp;
        this.creatorName = creatorName;
        this.updatorId = updatorId;
        this.updatorName = updatorName;
        this.enumId = enumId;
        this.key = key;
        this.value = value;
        this.creatorId = creatorId;
        this.text = text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enum_item.id
     *
     * @return the value of enum_item.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enum_item.createTimeStamp
     *
     * @return the value of enum_item.createTimeStamp
     *
     * @mbggenerated
     */
    public Date getCreateTimeStamp() {
        return createTimeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enum_item.updateTimeStamp
     *
     * @return the value of enum_item.updateTimeStamp
     *
     * @mbggenerated
     */
    public Date getUpdateTimeStamp() {
        return updateTimeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enum_item.creatorName
     *
     * @return the value of enum_item.creatorName
     *
     * @mbggenerated
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enum_item.updatorId
     *
     * @return the value of enum_item.updatorId
     *
     * @mbggenerated
     */
    public Long getUpdatorId() {
        return updatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enum_item.updatorName
     *
     * @return the value of enum_item.updatorName
     *
     * @mbggenerated
     */
    public String getUpdatorName() {
        return updatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enum_item.enumId
     *
     * @return the value of enum_item.enumId
     *
     * @mbggenerated
     */
    public Long getEnumId() {
        return enumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enum_item.key
     *
     * @return the value of enum_item.key
     *
     * @mbggenerated
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enum_item.value
     *
     * @return the value of enum_item.value
     *
     * @mbggenerated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enum_item.creatorId
     *
     * @return the value of enum_item.creatorId
     *
     * @mbggenerated
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enum_item.text
     *
     * @return the value of enum_item.text
     *
     * @mbggenerated
     */
    public String getText() {
        return text;
    }
}