package org.louis.hometutor.po;

import java.util.Date;

public class Hospital {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.createTimeStamp
     *
     * @mbggenerated
     */
    private Date createTimeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.updateTimeStamp
     *
     * @mbggenerated
     */
    private Date updateTimeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.province
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.zone
     *
     * @mbggenerated
     */
    private String zone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.provinceId
     *
     * @mbggenerated
     */
    private Long provinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.cityId
     *
     * @mbggenerated
     */
    private Long cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.zoneId
     *
     * @mbggenerated
     */
    private Long zoneId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbggenerated
     */
    public Hospital(Long id, Date createTimeStamp, Date updateTimeStamp, String name, String province, String city, String zone, Long provinceId, Long cityId, Long zoneId) {
        this.id = id;
        this.createTimeStamp = createTimeStamp;
        this.updateTimeStamp = updateTimeStamp;
        this.name = name;
        this.province = province;
        this.city = city;
        this.zone = zone;
        this.provinceId = provinceId;
        this.cityId = cityId;
        this.zoneId = zoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.id
     *
     * @return the value of hospital.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.createTimeStamp
     *
     * @return the value of hospital.createTimeStamp
     *
     * @mbggenerated
     */
    public Date getCreateTimeStamp() {
        return createTimeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.updateTimeStamp
     *
     * @return the value of hospital.updateTimeStamp
     *
     * @mbggenerated
     */
    public Date getUpdateTimeStamp() {
        return updateTimeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.name
     *
     * @return the value of hospital.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.province
     *
     * @return the value of hospital.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.city
     *
     * @return the value of hospital.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.zone
     *
     * @return the value of hospital.zone
     *
     * @mbggenerated
     */
    public String getZone() {
        return zone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.provinceId
     *
     * @return the value of hospital.provinceId
     *
     * @mbggenerated
     */
    public Long getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.cityId
     *
     * @return the value of hospital.cityId
     *
     * @mbggenerated
     */
    public Long getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.zoneId
     *
     * @return the value of hospital.zoneId
     *
     * @mbggenerated
     */
    public Long getZoneId() {
        return zoneId;
    }
}