package org.louis.hometutor.po;

import java.util.Date;

public class NeedNotify {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column need_notify.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column need_notify.createTimeStamp
     *
     * @mbggenerated
     */
    private Date createTimeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column need_notify.updateTimeStamp
     *
     * @mbggenerated
     */
    private Date updateTimeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column need_notify.causeObjectId
     *
     * @mbggenerated
     */
    private Long causeObjectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column need_notify.causeObjectType
     *
     * @mbggenerated
     */
    private Integer causeObjectType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column need_notify.isNotify
     *
     * @mbggenerated
     */
    private String isNotify;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table need_notify
     *
     * @mbggenerated
     */
    public NeedNotify(Long id, Date createTimeStamp, Date updateTimeStamp, Long causeObjectId, Integer causeObjectType, String isNotify) {
        this.id = id;
        this.createTimeStamp = createTimeStamp;
        this.updateTimeStamp = updateTimeStamp;
        this.causeObjectId = causeObjectId;
        this.causeObjectType = causeObjectType;
        this.isNotify = isNotify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column need_notify.id
     *
     * @return the value of need_notify.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column need_notify.createTimeStamp
     *
     * @return the value of need_notify.createTimeStamp
     *
     * @mbggenerated
     */
    public Date getCreateTimeStamp() {
        return createTimeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column need_notify.updateTimeStamp
     *
     * @return the value of need_notify.updateTimeStamp
     *
     * @mbggenerated
     */
    public Date getUpdateTimeStamp() {
        return updateTimeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column need_notify.causeObjectId
     *
     * @return the value of need_notify.causeObjectId
     *
     * @mbggenerated
     */
    public Long getCauseObjectId() {
        return causeObjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column need_notify.causeObjectType
     *
     * @return the value of need_notify.causeObjectType
     *
     * @mbggenerated
     */
    public Integer getCauseObjectType() {
        return causeObjectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column need_notify.isNotify
     *
     * @return the value of need_notify.isNotify
     *
     * @mbggenerated
     */
    public String getIsNotify() {
        return isNotify;
    }
}