package org.louis.hometutor.po;

import java.util.Date;

public class Payment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.createTimeStamp
     *
     * @mbggenerated
     */
    private Date createTimeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.updateTimeStamp
     *
     * @mbggenerated
     */
    private Date updateTimeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.orderId
     *
     * @mbggenerated
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.orderType
     *
     * @mbggenerated
     */
    private Integer orderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.payTimeStamp
     *
     * @mbggenerated
     */
    private Date payTimeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.fee
     *
     * @mbggenerated
     */
    private Long fee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.thirdPartyPlateFormId
     *
     * @mbggenerated
     */
    private String thirdPartyPlateFormId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.orderNo
     *
     * @mbggenerated
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.thirdPartyPlateFormPrepayId
     *
     * @mbggenerated
     */
    private String thirdPartyPlateFormPrepayId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.paymentNo
     *
     * @mbggenerated
     */
    private String paymentNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbggenerated
     */
    public Payment(Long id, Date createTimeStamp, Date updateTimeStamp, Long orderId, Integer orderType, Date payTimeStamp, Long fee, Integer status, String thirdPartyPlateFormId, String orderNo, String thirdPartyPlateFormPrepayId, String paymentNo) {
        this.id = id;
        this.createTimeStamp = createTimeStamp;
        this.updateTimeStamp = updateTimeStamp;
        this.orderId = orderId;
        this.orderType = orderType;
        this.payTimeStamp = payTimeStamp;
        this.fee = fee;
        this.status = status;
        this.thirdPartyPlateFormId = thirdPartyPlateFormId;
        this.orderNo = orderNo;
        this.thirdPartyPlateFormPrepayId = thirdPartyPlateFormPrepayId;
        this.paymentNo = paymentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.id
     *
     * @return the value of payment.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.createTimeStamp
     *
     * @return the value of payment.createTimeStamp
     *
     * @mbggenerated
     */
    public Date getCreateTimeStamp() {
        return createTimeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.updateTimeStamp
     *
     * @return the value of payment.updateTimeStamp
     *
     * @mbggenerated
     */
    public Date getUpdateTimeStamp() {
        return updateTimeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.orderId
     *
     * @return the value of payment.orderId
     *
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.orderType
     *
     * @return the value of payment.orderType
     *
     * @mbggenerated
     */
    public Integer getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.payTimeStamp
     *
     * @return the value of payment.payTimeStamp
     *
     * @mbggenerated
     */
    public Date getPayTimeStamp() {
        return payTimeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.fee
     *
     * @return the value of payment.fee
     *
     * @mbggenerated
     */
    public Long getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.status
     *
     * @return the value of payment.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.thirdPartyPlateFormId
     *
     * @return the value of payment.thirdPartyPlateFormId
     *
     * @mbggenerated
     */
    public String getThirdPartyPlateFormId() {
        return thirdPartyPlateFormId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.orderNo
     *
     * @return the value of payment.orderNo
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.thirdPartyPlateFormPrepayId
     *
     * @return the value of payment.thirdPartyPlateFormPrepayId
     *
     * @mbggenerated
     */
    public String getThirdPartyPlateFormPrepayId() {
        return thirdPartyPlateFormPrepayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.paymentNo
     *
     * @return the value of payment.paymentNo
     *
     * @mbggenerated
     */
    public String getPaymentNo() {
        return paymentNo;
    }
}