package org.louis.hometutor.po;

import java.util.Date;

public class PushMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push_message.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push_message.createTimeStamp
     *
     * @mbggenerated
     */
    private Date createTimeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push_message.updateTimeStamp
     *
     * @mbggenerated
     */
    private Date updateTimeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push_message.receiverId
     *
     * @mbggenerated
     */
    private Long receiverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push_message.receiverType
     *
     * @mbggenerated
     */
    private Integer receiverType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push_message.deviceInfo
     *
     * @mbggenerated
     */
    private String deviceInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push_message.pushToken
     *
     * @mbggenerated
     */
    private String pushToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push_message.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push_message.isSend
     *
     * @mbggenerated
     */
    private Boolean isSend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push_message.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_message
     *
     * @mbggenerated
     */
    public PushMessage(Long id, Date createTimeStamp, Date updateTimeStamp, Long receiverId, Integer receiverType, String deviceInfo, String pushToken, String content, Boolean isSend, String url) {
        this.id = id;
        this.createTimeStamp = createTimeStamp;
        this.updateTimeStamp = updateTimeStamp;
        this.receiverId = receiverId;
        this.receiverType = receiverType;
        this.deviceInfo = deviceInfo;
        this.pushToken = pushToken;
        this.content = content;
        this.isSend = isSend;
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push_message.id
     *
     * @return the value of push_message.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push_message.createTimeStamp
     *
     * @return the value of push_message.createTimeStamp
     *
     * @mbggenerated
     */
    public Date getCreateTimeStamp() {
        return createTimeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push_message.updateTimeStamp
     *
     * @return the value of push_message.updateTimeStamp
     *
     * @mbggenerated
     */
    public Date getUpdateTimeStamp() {
        return updateTimeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push_message.receiverId
     *
     * @return the value of push_message.receiverId
     *
     * @mbggenerated
     */
    public Long getReceiverId() {
        return receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push_message.receiverType
     *
     * @return the value of push_message.receiverType
     *
     * @mbggenerated
     */
    public Integer getReceiverType() {
        return receiverType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push_message.deviceInfo
     *
     * @return the value of push_message.deviceInfo
     *
     * @mbggenerated
     */
    public String getDeviceInfo() {
        return deviceInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push_message.pushToken
     *
     * @return the value of push_message.pushToken
     *
     * @mbggenerated
     */
    public String getPushToken() {
        return pushToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push_message.content
     *
     * @return the value of push_message.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push_message.isSend
     *
     * @return the value of push_message.isSend
     *
     * @mbggenerated
     */
    public Boolean getIsSend() {
        return isSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push_message.url
     *
     * @return the value of push_message.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }
}