package org.louis.hometutor.po;

import java.util.Date;

public class Topic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.createTimeStamp
     *
     * @mbggenerated
     */
    private Date createTimeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.updateTimeStamp
     *
     * @mbggenerated
     */
    private Date updateTimeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.creatorId
     *
     * @mbggenerated
     */
    private Long creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.creatorType
     *
     * @mbggenerated
     */
    private Integer creatorType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.updatorId
     *
     * @mbggenerated
     */
    private Long updatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.updatorType
     *
     * @mbggenerated
     */
    private Integer updatorType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.answerCount
     *
     * @mbggenerated
     */
    private Integer answerCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.lastReplyTimeStamp
     *
     * @mbggenerated
     */
    private Date lastReplyTimeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.lockExpireDate
     *
     * @mbggenerated
     */
    private Date lockExpireDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.isLock
     *
     * @mbggenerated
     */
    private Boolean isLock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.isShow
     *
     * @mbggenerated
     */
    private Boolean isShow;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated
     */
    public Topic(Long id, Date createTimeStamp, Date updateTimeStamp, Long creatorId, Integer creatorType, Long updatorId, Integer updatorType, Integer answerCount, Date lastReplyTimeStamp, Date lockExpireDate, Boolean isLock, Integer type, String content, String title, Boolean isShow) {
        this.id = id;
        this.createTimeStamp = createTimeStamp;
        this.updateTimeStamp = updateTimeStamp;
        this.creatorId = creatorId;
        this.creatorType = creatorType;
        this.updatorId = updatorId;
        this.updatorType = updatorType;
        this.answerCount = answerCount;
        this.lastReplyTimeStamp = lastReplyTimeStamp;
        this.lockExpireDate = lockExpireDate;
        this.isLock = isLock;
        this.type = type;
        this.content = content;
        this.title = title;
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.id
     *
     * @return the value of topic.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.createTimeStamp
     *
     * @return the value of topic.createTimeStamp
     *
     * @mbggenerated
     */
    public Date getCreateTimeStamp() {
        return createTimeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.updateTimeStamp
     *
     * @return the value of topic.updateTimeStamp
     *
     * @mbggenerated
     */
    public Date getUpdateTimeStamp() {
        return updateTimeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.creatorId
     *
     * @return the value of topic.creatorId
     *
     * @mbggenerated
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.creatorType
     *
     * @return the value of topic.creatorType
     *
     * @mbggenerated
     */
    public Integer getCreatorType() {
        return creatorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.updatorId
     *
     * @return the value of topic.updatorId
     *
     * @mbggenerated
     */
    public Long getUpdatorId() {
        return updatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.updatorType
     *
     * @return the value of topic.updatorType
     *
     * @mbggenerated
     */
    public Integer getUpdatorType() {
        return updatorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.answerCount
     *
     * @return the value of topic.answerCount
     *
     * @mbggenerated
     */
    public Integer getAnswerCount() {
        return answerCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.lastReplyTimeStamp
     *
     * @return the value of topic.lastReplyTimeStamp
     *
     * @mbggenerated
     */
    public Date getLastReplyTimeStamp() {
        return lastReplyTimeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.lockExpireDate
     *
     * @return the value of topic.lockExpireDate
     *
     * @mbggenerated
     */
    public Date getLockExpireDate() {
        return lockExpireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.isLock
     *
     * @return the value of topic.isLock
     *
     * @mbggenerated
     */
    public Boolean getIsLock() {
        return isLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.type
     *
     * @return the value of topic.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.content
     *
     * @return the value of topic.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.title
     *
     * @return the value of topic.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.isShow
     *
     * @return the value of topic.isShow
     *
     * @mbggenerated
     */
    public Boolean getIsShow() {
        return isShow;
    }
}