package org.louis.hometutor.po;

import java.util.Date;

public class UnVerifyArticleResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column un_verify_article_resource.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column un_verify_article_resource.createTimeStamp
     *
     * @mbggenerated
     */
    private Date createTimeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column un_verify_article_resource.updateTimeStamp
     *
     * @mbggenerated
     */
    private Date updateTimeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column un_verify_article_resource.resourceUrl
     *
     * @mbggenerated
     */
    private String resourceUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column un_verify_article_resource.unVerifyArticleId
     *
     * @mbggenerated
     */
    private Long unVerifyArticleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table un_verify_article_resource
     *
     * @mbggenerated
     */
    public UnVerifyArticleResource(Long id, Date createTimeStamp, Date updateTimeStamp, String resourceUrl, Long unVerifyArticleId) {
        this.id = id;
        this.createTimeStamp = createTimeStamp;
        this.updateTimeStamp = updateTimeStamp;
        this.resourceUrl = resourceUrl;
        this.unVerifyArticleId = unVerifyArticleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column un_verify_article_resource.id
     *
     * @return the value of un_verify_article_resource.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column un_verify_article_resource.createTimeStamp
     *
     * @return the value of un_verify_article_resource.createTimeStamp
     *
     * @mbggenerated
     */
    public Date getCreateTimeStamp() {
        return createTimeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column un_verify_article_resource.updateTimeStamp
     *
     * @return the value of un_verify_article_resource.updateTimeStamp
     *
     * @mbggenerated
     */
    public Date getUpdateTimeStamp() {
        return updateTimeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column un_verify_article_resource.resourceUrl
     *
     * @return the value of un_verify_article_resource.resourceUrl
     *
     * @mbggenerated
     */
    public String getResourceUrl() {
        return resourceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column un_verify_article_resource.unVerifyArticleId
     *
     * @return the value of un_verify_article_resource.unVerifyArticleId
     *
     * @mbggenerated
     */
    public Long getUnVerifyArticleId() {
        return unVerifyArticleId;
    }
}