package com.foo.tourist.dao;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;
import org.louis.hometutor.po.AccessTokenLog;
import org.louis.hometutor.po.AccessTokenLogExample;

public interface AccessTokenLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_token_log
     *
     * @mbggenerated
     */
    @SelectProvider(type=AccessTokenLogSqlProvider.class, method="countByExample")
    int countByExample(AccessTokenLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_token_log
     *
     * @mbggenerated
     */
    @SelectProvider(type=AccessTokenLogSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="key", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="accessToken", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP)
    })
    List<AccessTokenLog> selectByExample(AccessTokenLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_token_log
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "\"id\", \"key\", \"accessToken\", \"createTimeStamp\"",
        "from \"access_token_log\"",
        "where \"id\" = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="key", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="accessToken", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP)
    })
    AccessTokenLog selectByPrimaryKey(Long id);
}