package com.foo.tourist.dao;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;
import org.louis.hometutor.po.Address;
import org.louis.hometutor.po.AddressExample;

public interface AddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbggenerated
     */
    @SelectProvider(type=AddressSqlProvider.class, method="countByExample")
    int countByExample(AddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbggenerated
     */
    @SelectProvider(type=AddressSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="ownerId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="ownerType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="detailAddress", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="province", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="city", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="zone", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="provinceId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="cityId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="zoneId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="receiverName", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="receiverContact", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<Address> selectByExample(AddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "\"id\", \"createTimeStamp\", \"updateTimeStamp\", \"ownerId\", \"ownerType\", ",
        "\"detailAddress\", \"province\", \"city\", \"zone\", \"provinceId\", \"cityId\", ",
        "\"zoneId\", \"receiverName\", \"receiverContact\"",
        "from \"address\"",
        "where \"id\" = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="ownerId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="ownerType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="detailAddress", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="province", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="city", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="zone", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="provinceId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="cityId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="zoneId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="receiverName", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="receiverContact", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    Address selectByPrimaryKey(Long id);
}