package com.foo.tourist.dao;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;
import org.louis.hometutor.po.ArticleResource;
import org.louis.hometutor.po.ArticleResourceExample;

public interface ArticleResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_resource
     *
     * @mbggenerated
     */
    @SelectProvider(type=ArticleResourceSqlProvider.class, method="countByExample")
    int countByExample(ArticleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_resource
     *
     * @mbggenerated
     */
    @SelectProvider(type=ArticleResourceSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="resourceUrl", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="articleId", javaType=Long.class, jdbcType=JdbcType.BIGINT)
    })
    List<ArticleResource> selectByExample(ArticleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_resource
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "\"id\", \"createTimeStamp\", \"updateTimeStamp\", \"resourceUrl\", \"articleId\"",
        "from \"article_resource\"",
        "where \"id\" = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="resourceUrl", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="articleId", javaType=Long.class, jdbcType=JdbcType.BIGINT)
    })
    ArticleResource selectByPrimaryKey(Long id);
}