package com.foo.tourist.dao;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;
import org.louis.hometutor.po.Auth;
import org.louis.hometutor.po.AuthExample;

public interface AuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth
     *
     * @mbggenerated
     */
    @SelectProvider(type=AuthSqlProvider.class, method="countByExample")
    int countByExample(AuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth
     *
     * @mbggenerated
     */
    @SelectProvider(type=AuthSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="text", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="key", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="type", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="url", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="sort", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="enable", javaType=Boolean.class, jdbcType=JdbcType.BIT),
        @Arg(column="desc", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="parentAuthId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="keypath", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="isdel", javaType=Boolean.class, jdbcType=JdbcType.BIT),
        @Arg(column="updatorId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="creatorId", javaType=Long.class, jdbcType=JdbcType.BIGINT)
    })
    List<Auth> selectByExample(AuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "\"id\", \"createTimeStamp\", \"updateTimeStamp\", \"text\", \"key\", \"type\", ",
        "\"url\", \"sort\", \"enable\", \"desc\", \"parentAuthId\", \"keypath\", \"isdel\", ",
        "\"updatorId\", \"creatorId\"",
        "from \"auth\"",
        "where \"id\" = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="text", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="key", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="type", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="url", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="sort", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="enable", javaType=Boolean.class, jdbcType=JdbcType.BIT),
        @Arg(column="desc", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="parentAuthId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="keypath", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="isdel", javaType=Boolean.class, jdbcType=JdbcType.BIT),
        @Arg(column="updatorId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="creatorId", javaType=Long.class, jdbcType=JdbcType.BIGINT)
    })
    Auth selectByPrimaryKey(Long id);
}