package com.foo.tourist.dao;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;
import org.louis.hometutor.po.AuthorityVerify;
import org.louis.hometutor.po.AuthorityVerifyExample;

public interface AuthorityVerifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority_verify
     *
     * @mbggenerated
     */
    @SelectProvider(type=AuthorityVerifySqlProvider.class, method="countByExample")
    int countByExample(AuthorityVerifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority_verify
     *
     * @mbggenerated
     */
    @SelectProvider(type=AuthorityVerifySqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="status", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="verifyTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="doctorId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="resultDesc", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<AuthorityVerify> selectByExample(AuthorityVerifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority_verify
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "\"id\", \"createTimeStamp\", \"updateTimeStamp\", \"status\", \"verifyTimeStamp\", ",
        "\"doctorId\", \"resultDesc\"",
        "from \"authority_verify\"",
        "where \"id\" = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="status", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="verifyTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="doctorId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="resultDesc", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    AuthorityVerify selectByPrimaryKey(Long id);
}