package com.foo.tourist.dao;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;
import org.louis.hometutor.po.Banner;
import org.louis.hometutor.po.BannerExample;

public interface BannerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banner
     *
     * @mbggenerated
     */
    @SelectProvider(type=BannerSqlProvider.class, method="countByExample")
    int countByExample(BannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banner
     *
     * @mbggenerated
     */
    @SelectProvider(type=BannerSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="creatorId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="updatorId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="creator", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="updator", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="bannerType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="bannerDesc", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<Banner> selectByExample(BannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banner
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "\"id\", \"createTimeStamp\", \"updateTimeStamp\", \"creatorId\", \"updatorId\", ",
        "\"creator\", \"updator\", \"bannerType\", \"bannerDesc\"",
        "from \"banner\"",
        "where \"id\" = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="creatorId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="updatorId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="creator", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="updator", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="bannerType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="bannerDesc", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    Banner selectByPrimaryKey(Long id);
}