package com.foo.tourist.dao;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;
import org.louis.hometutor.po.BonusPointOrder;
import org.louis.hometutor.po.BonusPointOrderExample;

public interface BonusPointOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bonus_point_order
     *
     * @mbggenerated
     */
    @SelectProvider(type=BonusPointOrderSqlProvider.class, method="countByExample")
    int countByExample(BonusPointOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bonus_point_order
     *
     * @mbggenerated
     */
    @SelectProvider(type=BonusPointOrderSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="consumerName", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="consumerId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="consumerType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="consumeBonusPoint", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="thirdPlatformOrderNo", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="status", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="no", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="fee", javaType=Long.class, jdbcType=JdbcType.BIGINT)
    })
    List<BonusPointOrder> selectByExample(BonusPointOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bonus_point_order
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "\"id\", \"createTimeStamp\", \"updateTimeStamp\", \"consumerName\", \"consumerId\", ",
        "\"consumerType\", \"consumeBonusPoint\", \"thirdPlatformOrderNo\", \"status\", ",
        "\"no\", \"fee\"",
        "from \"bonus_point_order\"",
        "where \"id\" = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="consumerName", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="consumerId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="consumerType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="consumeBonusPoint", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="thirdPlatformOrderNo", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="status", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="no", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="fee", javaType=Long.class, jdbcType=JdbcType.BIGINT)
    })
    BonusPointOrder selectByPrimaryKey(Long id);
}