package com.foo.tourist.dao;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;
import org.louis.hometutor.po.ChargeTemplate;
import org.louis.hometutor.po.ChargeTemplateExample;

public interface ChargeTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_template
     *
     * @mbggenerated
     */
    @SelectProvider(type=ChargeTemplateSqlProvider.class, method="countByExample")
    int countByExample(ChargeTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_template
     *
     * @mbggenerated
     */
    @SelectProvider(type=ChargeTemplateSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="fee", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="status", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="type", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="doctorId", javaType=Long.class, jdbcType=JdbcType.BIGINT)
    })
    List<ChargeTemplate> selectByExample(ChargeTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_template
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "\"id\", \"createTimeStamp\", \"updateTimeStamp\", \"fee\", \"status\", \"type\", ",
        "\"doctorId\"",
        "from \"charge_template\"",
        "where \"id\" = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="fee", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="status", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="type", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="doctorId", javaType=Long.class, jdbcType=JdbcType.BIGINT)
    })
    ChargeTemplate selectByPrimaryKey(Long id);
}