package com.foo.tourist.dao;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;
import org.louis.hometutor.po.Comment;
import org.louis.hometutor.po.CommentExample;

public interface CommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    @SelectProvider(type=CommentSqlProvider.class, method="countByExample")
    int countByExample(CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    @SelectProvider(type=CommentSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="posterId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="posterType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="replyTargetId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="replyTargetType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="commentTargetId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="commentTargetType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="content", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<Comment> selectByExample(CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "\"id\", \"createTimeStamp\", \"updateTimeStamp\", \"posterId\", \"posterType\", ",
        "\"replyTargetId\", \"replyTargetType\", \"commentTargetId\", \"commentTargetType\", ",
        "\"content\"",
        "from \"comment\"",
        "where \"id\" = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="posterId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="posterType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="replyTargetId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="replyTargetType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="commentTargetId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="commentTargetType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="content", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    Comment selectByPrimaryKey(Long id);
}