package com.foo.tourist.dao;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;
import org.louis.hometutor.po.CustomerService;
import org.louis.hometutor.po.CustomerServiceExample;

public interface CustomerServiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_service
     *
     * @mbggenerated
     */
    @SelectProvider(type=CustomerServiceSqlProvider.class, method="countByExample")
    int countByExample(CustomerServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_service
     *
     * @mbggenerated
     */
    @SelectProvider(type=CustomerServiceSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="creator", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="updator", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="chatId", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="onDuty", javaType=Boolean.class, jdbcType=JdbcType.BIT)
    })
    List<CustomerService> selectByExample(CustomerServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_service
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "\"id\", \"createTimeStamp\", \"updateTimeStamp\", \"creator\", \"updator\", ",
        "\"name\", \"chatId\", \"onDuty\"",
        "from \"customer_service\"",
        "where \"id\" = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="creator", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="updator", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="chatId", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="onDuty", javaType=Boolean.class, jdbcType=JdbcType.BIT)
    })
    CustomerService selectByPrimaryKey(Long id);
}