package com.foo.tourist.dao;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;
import org.louis.hometutor.po.DeviceInfo;
import org.louis.hometutor.po.DeviceInfoExample;

public interface DeviceInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated
     */
    @SelectProvider(type=DeviceInfoSqlProvider.class, method="countByExample")
    int countByExample(DeviceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated
     */
    @SelectProvider(type=DeviceInfoSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="deviceType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="userId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="deviceInfo", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="userType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="pushToken", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<DeviceInfo> selectByExample(DeviceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "\"id\", \"createTimeStamp\", \"updateTimeStamp\", \"deviceType\", \"userId\", ",
        "\"deviceInfo\", \"userType\", \"pushToken\"",
        "from \"device_info\"",
        "where \"id\" = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="deviceType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="userId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="deviceInfo", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="userType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="pushToken", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    DeviceInfo selectByPrimaryKey(Long id);
}