package com.foo.tourist.dao;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;
import org.louis.hometutor.po.DoctorServeOrder;
import org.louis.hometutor.po.DoctorServeOrderExample;

public interface DoctorServeOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_serve_order
     *
     * @mbggenerated
     */
    @SelectProvider(type=DoctorServeOrderSqlProvider.class, method="countByExample")
    int countByExample(DoctorServeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_serve_order
     *
     * @mbggenerated
     */
    @SelectProvider(type=DoctorServeOrderSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="settlementStatus", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="type", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="patientDoctorId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="count", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="fee", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="no", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="serverStartTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="serverEndTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="payStatus", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="refundStatus", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="orderStatus", javaType=Integer.class, jdbcType=JdbcType.INTEGER)
    })
    List<DoctorServeOrder> selectByExample(DoctorServeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_serve_order
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "\"id\", \"createTimeStamp\", \"updateTimeStamp\", \"settlementStatus\", \"type\", ",
        "\"patientDoctorId\", \"count\", \"fee\", \"no\", \"serverStartTimeStamp\", \"serverEndTimeStamp\", ",
        "\"payStatus\", \"refundStatus\", \"orderStatus\"",
        "from \"doctor_serve_order\"",
        "where \"id\" = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="settlementStatus", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="type", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="patientDoctorId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="count", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="fee", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="no", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="serverStartTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="serverEndTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="payStatus", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="refundStatus", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="orderStatus", javaType=Integer.class, jdbcType=JdbcType.INTEGER)
    })
    DoctorServeOrder selectByPrimaryKey(Long id);
}