package com.foo.tourist.dao;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;
import org.louis.hometutor.po.EnumItem;
import org.louis.hometutor.po.EnumItemExample;

public interface EnumItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enum_item
     *
     * @mbggenerated
     */
    @SelectProvider(type=EnumItemSqlProvider.class, method="countByExample")
    int countByExample(EnumItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enum_item
     *
     * @mbggenerated
     */
    @SelectProvider(type=EnumItemSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="creatorName", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="updatorId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="updatorName", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="enumId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="key", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="value", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="creatorId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="text", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<EnumItem> selectByExample(EnumItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enum_item
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "\"id\", \"createTimeStamp\", \"updateTimeStamp\", \"creatorName\", \"updatorId\", ",
        "\"updatorName\", \"enumId\", \"key\", \"value\", \"creatorId\", \"text\"",
        "from \"enum_item\"",
        "where \"id\" = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="creatorName", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="updatorId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="updatorName", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="enumId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="key", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="value", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="creatorId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="text", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    EnumItem selectByPrimaryKey(Long id);
}