package com.foo.tourist.dao;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;
import org.louis.hometutor.po.ExceptionFailLog;
import org.louis.hometutor.po.ExceptionFailLogExample;

public interface ExceptionFailLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_fail_log
     *
     * @mbggenerated
     */
    @SelectProvider(type=ExceptionFailLogSqlProvider.class, method="countByExample")
    int countByExample(ExceptionFailLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_fail_log
     *
     * @mbggenerated
     */
    @SelectProvider(type=ExceptionFailLogSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="userName", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="apiUrl", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="isdone", javaType=Boolean.class, jdbcType=JdbcType.BIT),
        @Arg(column="parameters", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="failAction", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="desc", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<ExceptionFailLog> selectByExample(ExceptionFailLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_fail_log
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "\"id\", \"userName\", \"apiUrl\", \"isdone\", \"parameters\", \"failAction\", ",
        "\"createTimeStamp\", \"desc\"",
        "from \"exception_fail_log\"",
        "where \"id\" = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="userName", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="apiUrl", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="isdone", javaType=Boolean.class, jdbcType=JdbcType.BIT),
        @Arg(column="parameters", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="failAction", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="desc", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    ExceptionFailLog selectByPrimaryKey(Long id);
}