package com.foo.tourist.dao;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;
import org.louis.hometutor.po.FreeFollowUpTemplate;
import org.louis.hometutor.po.FreeFollowUpTemplateExample;

public interface FreeFollowUpTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table free_follow_up_template
     *
     * @mbggenerated
     */
    @SelectProvider(type=FreeFollowUpTemplateSqlProvider.class, method="countByExample")
    int countByExample(FreeFollowUpTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table free_follow_up_template
     *
     * @mbggenerated
     */
    @SelectProvider(type=FreeFollowUpTemplateSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="count", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="docId", javaType=Long.class, jdbcType=JdbcType.BIGINT)
    })
    List<FreeFollowUpTemplate> selectByExample(FreeFollowUpTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table free_follow_up_template
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "\"id\", \"createTimeStamp\", \"updateTimeStamp\", \"count\", \"docId\"",
        "from \"free_follow_up_template\"",
        "where \"id\" = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="count", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="docId", javaType=Long.class, jdbcType=JdbcType.BIGINT)
    })
    FreeFollowUpTemplate selectByPrimaryKey(Long id);
}