package com.foo.tourist.dao;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;
import org.louis.hometutor.po.FreeFollowUpLog;
import org.louis.hometutor.po.FreeFollowUpLogExample;

public interface FreeFollowUpLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table free_follow_up_log
     *
     * @mbggenerated
     */
    @SelectProvider(type=FreeFollowUpLogSqlProvider.class, method="countByExample")
    int countByExample(FreeFollowUpLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table free_follow_up_log
     *
     * @mbggenerated
     */
    @SelectProvider(type=FreeFollowUpLogSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="count", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="patientDoctorId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="reason", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<FreeFollowUpLog> selectByExample(FreeFollowUpLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table free_follow_up_log
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "\"id\", \"createTimeStamp\", \"updateTimeStamp\", \"count\", \"patientDoctorId\", ",
        "\"reason\"",
        "from \"free_follow_up_log\"",
        "where \"id\" = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="count", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="patientDoctorId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="reason", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    FreeFollowUpLog selectByPrimaryKey(Long id);
}