package com.foo.tourist.dao;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;
import org.louis.hometutor.po.Hospital;
import org.louis.hometutor.po.HospitalExample;

public interface HospitalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbggenerated
     */
    @SelectProvider(type=HospitalSqlProvider.class, method="countByExample")
    int countByExample(HospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbggenerated
     */
    @SelectProvider(type=HospitalSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="province", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="city", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="zone", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="provinceId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="cityId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="zoneId", javaType=Long.class, jdbcType=JdbcType.BIGINT)
    })
    List<Hospital> selectByExample(HospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "\"id\", \"createTimeStamp\", \"updateTimeStamp\", \"name\", \"province\", \"city\", ",
        "\"zone\", \"provinceId\", \"cityId\", \"zoneId\"",
        "from \"hospital\"",
        "where \"id\" = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="province", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="city", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="zone", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="provinceId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="cityId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="zoneId", javaType=Long.class, jdbcType=JdbcType.BIGINT)
    })
    Hospital selectByPrimaryKey(Long id);
}