package com.foo.tourist.dao;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;
import org.louis.hometutor.po.InternalUser;
import org.louis.hometutor.po.InternalUserExample;

public interface InternalUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internal_user
     *
     * @mbggenerated
     */
    @SelectProvider(type=InternalUserSqlProvider.class, method="countByExample")
    int countByExample(InternalUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internal_user
     *
     * @mbggenerated
     */
    @SelectProvider(type=InternalUserSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="userName", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="password", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="realName", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="phoneNo", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="isdel", javaType=Boolean.class, jdbcType=JdbcType.BIT),
        @Arg(column="updatorId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="creatorId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="no", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<InternalUser> selectByExample(InternalUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internal_user
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "\"id\", \"createTimeStamp\", \"updateTimeStamp\", \"userName\", \"password\", ",
        "\"realName\", \"phoneNo\", \"isdel\", \"updatorId\", \"creatorId\", \"no\"",
        "from \"internal_user\"",
        "where \"id\" = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="userName", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="password", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="realName", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="phoneNo", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="isdel", javaType=Boolean.class, jdbcType=JdbcType.BIT),
        @Arg(column="updatorId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="creatorId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="no", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    InternalUser selectByPrimaryKey(Long id);
}