package com.foo.tourist.dao;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;
import org.louis.hometutor.po.InternalUserRole;
import org.louis.hometutor.po.InternalUserRoleExample;

public interface InternalUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internal_user_role
     *
     * @mbggenerated
     */
    @SelectProvider(type=InternalUserRoleSqlProvider.class, method="countByExample")
    int countByExample(InternalUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internal_user_role
     *
     * @mbggenerated
     */
    @SelectProvider(type=InternalUserRoleSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="internalUserId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="roleId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="isdel", javaType=Boolean.class, jdbcType=JdbcType.BIT),
        @Arg(column="updatorId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="creatorId", javaType=Long.class, jdbcType=JdbcType.BIGINT)
    })
    List<InternalUserRole> selectByExample(InternalUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internal_user_role
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "\"id\", \"createTimeStamp\", \"updateTimeStamp\", \"internalUserId\", \"roleId\", ",
        "\"isdel\", \"updatorId\", \"creatorId\"",
        "from \"internal_user_role\"",
        "where \"id\" = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="internalUserId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="roleId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="isdel", javaType=Boolean.class, jdbcType=JdbcType.BIT),
        @Arg(column="updatorId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="creatorId", javaType=Long.class, jdbcType=JdbcType.BIGINT)
    })
    InternalUserRole selectByPrimaryKey(Long id);
}