package com.foo.tourist.dao;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;
import org.louis.hometutor.po.LeanCloudSession;
import org.louis.hometutor.po.LeanCloudSessionExample;

public interface LeanCloudSessionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lean_cloud_session
     *
     * @mbggenerated
     */
    @SelectProvider(type=LeanCloudSessionSqlProvider.class, method="countByExample")
    int countByExample(LeanCloudSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lean_cloud_session
     *
     * @mbggenerated
     */
    @SelectProvider(type=LeanCloudSessionSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="sessionUserId", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="sessionId", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<LeanCloudSession> selectByExample(LeanCloudSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lean_cloud_session
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "\"id\", \"createTimeStamp\", \"updateTimeStamp\", \"sessionUserId\", \"sessionId\"",
        "from \"lean_cloud_session\"",
        "where \"id\" = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="sessionUserId", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="sessionId", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    LeanCloudSession selectByPrimaryKey(Long id);
}