package com.foo.tourist.dao;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;
import org.louis.hometutor.po.Like;
import org.louis.hometutor.po.LikeExample;

public interface LikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like
     *
     * @mbggenerated
     */
    @SelectProvider(type=LikeSqlProvider.class, method="countByExample")
    int countByExample(LikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like
     *
     * @mbggenerated
     */
    @SelectProvider(type=LikeSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="likerId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="likerType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="likeObjectId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="likeObjectType", javaType=Integer.class, jdbcType=JdbcType.INTEGER)
    })
    List<Like> selectByExample(LikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "\"id\", \"createTimeStamp\", \"updateTimeStamp\", \"likerId\", \"likerType\", ",
        "\"likeObjectId\", \"likeObjectType\"",
        "from \"like\"",
        "where \"id\" = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="likerId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="likerType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="likeObjectId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="likeObjectType", javaType=Integer.class, jdbcType=JdbcType.INTEGER)
    })
    Like selectByPrimaryKey(Long id);
}