package com.foo.tourist.dao;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;
import org.louis.hometutor.po.Message;
import org.louis.hometutor.po.MessageExample;

public interface MessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated
     */
    @SelectProvider(type=MessageSqlProvider.class, method="countByExample")
    int countByExample(MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated
     */
    @SelectProvider(type=MessageSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="senderId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="receiverId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="content", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="messageType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="isRead", javaType=Boolean.class, jdbcType=JdbcType.BIT),
        @Arg(column="readTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="senderType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="receiverType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="contentLength", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="isSystemSend", javaType=Boolean.class, jdbcType=JdbcType.BIT)
    })
    List<Message> selectByExample(MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "\"id\", \"createTimeStamp\", \"updateTimeStamp\", \"senderId\", \"receiverId\", ",
        "\"content\", \"messageType\", \"isRead\", \"readTimeStamp\", \"senderType\", ",
        "\"receiverType\", \"contentLength\", \"isSystemSend\"",
        "from \"message\"",
        "where \"id\" = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="senderId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="receiverId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="content", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="messageType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="isRead", javaType=Boolean.class, jdbcType=JdbcType.BIT),
        @Arg(column="readTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="senderType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="receiverType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="contentLength", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="isSystemSend", javaType=Boolean.class, jdbcType=JdbcType.BIT)
    })
    Message selectByPrimaryKey(Long id);
}