package com.foo.tourist.dao;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;
import org.louis.hometutor.po.NeedNotify;
import org.louis.hometutor.po.NeedNotifyExample;

public interface NeedNotifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table need_notify
     *
     * @mbggenerated
     */
    @SelectProvider(type=NeedNotifySqlProvider.class, method="countByExample")
    int countByExample(NeedNotifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table need_notify
     *
     * @mbggenerated
     */
    @SelectProvider(type=NeedNotifySqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="causeObjectId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="causeObjectType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="isNotify", javaType=String.class, jdbcType=JdbcType.CHAR)
    })
    List<NeedNotify> selectByExample(NeedNotifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table need_notify
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "\"id\", \"createTimeStamp\", \"updateTimeStamp\", \"causeObjectId\", \"causeObjectType\", ",
        "\"isNotify\"",
        "from \"need_notify\"",
        "where \"id\" = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="causeObjectId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="causeObjectType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="isNotify", javaType=String.class, jdbcType=JdbcType.CHAR)
    })
    NeedNotify selectByPrimaryKey(Long id);
}