package com.foo.tourist.dao;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;
import org.louis.hometutor.po.ObjectTag;
import org.louis.hometutor.po.ObjectTagExample;

public interface ObjectTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table object_tag
     *
     * @mbggenerated
     */
    @SelectProvider(type=ObjectTagSqlProvider.class, method="countByExample")
    int countByExample(ObjectTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table object_tag
     *
     * @mbggenerated
     */
    @SelectProvider(type=ObjectTagSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="objectId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="objectType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="tagName", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<ObjectTag> selectByExample(ObjectTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table object_tag
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "\"id\", \"createTimeStamp\", \"updateTimeStamp\", \"objectId\", \"objectType\", ",
        "\"tagName\"",
        "from \"object_tag\"",
        "where \"id\" = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="objectId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="objectType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="tagName", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    ObjectTag selectByPrimaryKey(Long id);
}