package com.foo.tourist.dao;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;
import org.louis.hometutor.po.OperationOrderResource;
import org.louis.hometutor.po.OperationOrderResourceExample;

public interface OperationOrderResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_order_resource
     *
     * @mbggenerated
     */
    @SelectProvider(type=OperationOrderResourceSqlProvider.class, method="countByExample")
    int countByExample(OperationOrderResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_order_resource
     *
     * @mbggenerated
     */
    @SelectProvider(type=OperationOrderResourceSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="resourceUrl", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="operationOrderId", javaType=Long.class, jdbcType=JdbcType.BIGINT)
    })
    List<OperationOrderResource> selectByExample(OperationOrderResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_order_resource
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "\"id\", \"createTimeStamp\", \"updateTimeStamp\", \"resourceUrl\", \"operationOrderId\"",
        "from \"operation_order_resource\"",
        "where \"id\" = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="resourceUrl", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="operationOrderId", javaType=Long.class, jdbcType=JdbcType.BIGINT)
    })
    OperationOrderResource selectByPrimaryKey(Long id);
}