package com.foo.tourist.dao;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;
import org.louis.hometutor.po.OperationOrder;
import org.louis.hometutor.po.OperationOrderExample;

public interface OperationOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_order
     *
     * @mbggenerated
     */
    @SelectProvider(type=OperationOrderSqlProvider.class, method="countByExample")
    int countByExample(OperationOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_order
     *
     * @mbggenerated
     */
    @SelectProvider(type=OperationOrderSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="patientId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="doctorName", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="hospital", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="department", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="no", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="fee", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="orderStatus", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="payStatus", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="refundStatus", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="diseaseDiagnosis", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="desc", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="phoneNo", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="surgeryPatientName", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<OperationOrder> selectByExample(OperationOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_order
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "\"id\", \"createTimeStamp\", \"updateTimeStamp\", \"patientId\", \"doctorName\", ",
        "\"hospital\", \"department\", \"no\", \"fee\", \"orderStatus\", \"payStatus\", ",
        "\"refundStatus\", \"diseaseDiagnosis\", \"desc\", \"phoneNo\", \"surgeryPatientName\"",
        "from \"operation_order\"",
        "where \"id\" = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="patientId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="doctorName", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="hospital", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="department", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="no", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="fee", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="orderStatus", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="payStatus", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="refundStatus", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="diseaseDiagnosis", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="desc", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="phoneNo", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="surgeryPatientName", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    OperationOrder selectByPrimaryKey(Long id);
}