package com.foo.tourist.dao;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;
import org.louis.hometutor.po.Patient;
import org.louis.hometutor.po.PatientExample;

public interface PatientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient
     *
     * @mbggenerated
     */
    @SelectProvider(type=PatientSqlProvider.class, method="countByExample")
    int countByExample(PatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient
     *
     * @mbggenerated
     */
    @SelectProvider(type=PatientSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="realName", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="externalUserId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="wechatId", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="wechatNo", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="phoneNo", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="doctorCount", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="iconUrl", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="no", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="sex", javaType=Boolean.class, jdbcType=JdbcType.BIT),
        @Arg(column="birthdayDate", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="enable", javaType=Boolean.class, jdbcType=JdbcType.BIT),
        @Arg(column="disabledReason", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="userId", javaType=Long.class, jdbcType=JdbcType.BIGINT)
    })
    List<Patient> selectByExample(PatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "\"id\", \"createTimeStamp\", \"updateTimeStamp\", \"realName\", \"externalUserId\", ",
        "\"wechatId\", \"wechatNo\", \"phoneNo\", \"doctorCount\", \"iconUrl\", \"no\", ",
        "\"sex\", \"birthdayDate\", \"enable\", \"disabledReason\", \"userId\"",
        "from \"patient\"",
        "where \"id\" = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="realName", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="externalUserId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="wechatId", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="wechatNo", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="phoneNo", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="doctorCount", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="iconUrl", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="no", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="sex", javaType=Boolean.class, jdbcType=JdbcType.BIT),
        @Arg(column="birthdayDate", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="enable", javaType=Boolean.class, jdbcType=JdbcType.BIT),
        @Arg(column="disabledReason", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="userId", javaType=Long.class, jdbcType=JdbcType.BIGINT)
    })
    Patient selectByPrimaryKey(Long id);
}