package com.foo.tourist.dao;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;
import org.louis.hometutor.po.PatientCharge;
import org.louis.hometutor.po.PatientChargeExample;

public interface PatientChargeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_charge
     *
     * @mbggenerated
     */
    @SelectProvider(type=PatientChargeSqlProvider.class, method="countByExample")
    int countByExample(PatientChargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_charge
     *
     * @mbggenerated
     */
    @SelectProvider(type=PatientChargeSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="patientDoctorId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="fee", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="type", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="enable", javaType=Boolean.class, jdbcType=JdbcType.BIT)
    })
    List<PatientCharge> selectByExample(PatientChargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_charge
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "\"id\", \"createTimeStamp\", \"updateTimeStamp\", \"patientDoctorId\", \"fee\", ",
        "\"type\", \"enable\"",
        "from \"patient_charge\"",
        "where \"id\" = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="patientDoctorId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="fee", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="type", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="enable", javaType=Boolean.class, jdbcType=JdbcType.BIT)
    })
    PatientCharge selectByPrimaryKey(Long id);
}