package com.foo.tourist.dao;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;
import org.louis.hometutor.po.PatientDoctorServe;
import org.louis.hometutor.po.PatientDoctorServeExample;

public interface PatientDoctorServeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_doctor_serve
     *
     * @mbggenerated
     */
    @SelectProvider(type=PatientDoctorServeSqlProvider.class, method="countByExample")
    int countByExample(PatientDoctorServeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_doctor_serve
     *
     * @mbggenerated
     */
    @SelectProvider(type=PatientDoctorServeSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="beginTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="endTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="type", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="restCount", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="status", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="patientDoctorId", javaType=Long.class, jdbcType=JdbcType.BIGINT)
    })
    List<PatientDoctorServe> selectByExample(PatientDoctorServeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_doctor_serve
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "\"id\", \"createTimeStamp\", \"updateTimeStamp\", \"beginTimeStamp\", \"endTimeStamp\", ",
        "\"type\", \"restCount\", \"status\", \"patientDoctorId\"",
        "from \"patient_doctor_serve\"",
        "where \"id\" = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="beginTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="endTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="type", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="restCount", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="status", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="patientDoctorId", javaType=Long.class, jdbcType=JdbcType.BIGINT)
    })
    PatientDoctorServe selectByPrimaryKey(Long id);
}