package com.foo.tourist.dao;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;
import org.louis.hometutor.po.Payment;
import org.louis.hometutor.po.PaymentExample;

public interface PaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbggenerated
     */
    @SelectProvider(type=PaymentSqlProvider.class, method="countByExample")
    int countByExample(PaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbggenerated
     */
    @SelectProvider(type=PaymentSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="orderId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="orderType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="payTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="fee", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="status", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="thirdPartyPlateFormId", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="orderNo", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="thirdPartyPlateFormPrepayId", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="paymentNo", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<Payment> selectByExample(PaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "\"id\", \"createTimeStamp\", \"updateTimeStamp\", \"orderId\", \"orderType\", ",
        "\"payTimeStamp\", \"fee\", \"status\", \"thirdPartyPlateFormId\", \"orderNo\", ",
        "\"thirdPartyPlateFormPrepayId\", \"paymentNo\"",
        "from \"payment\"",
        "where \"id\" = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="orderId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="orderType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="payTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="fee", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="status", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="thirdPartyPlateFormId", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="orderNo", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="thirdPartyPlateFormPrepayId", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="paymentNo", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    Payment selectByPrimaryKey(Long id);
}