package com.foo.tourist.dao;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;
import org.louis.hometutor.po.PhoneMessage;
import org.louis.hometutor.po.PhoneMessageExample;

public interface PhoneMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_message
     *
     * @mbggenerated
     */
    @SelectProvider(type=PhoneMessageSqlProvider.class, method="countByExample")
    int countByExample(PhoneMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_message
     *
     * @mbggenerated
     */
    @SelectProvider(type=PhoneMessageSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="content", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="isSend", javaType=Boolean.class, jdbcType=JdbcType.BIT),
        @Arg(column="phoneNo", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="desc", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<PhoneMessage> selectByExample(PhoneMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_message
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "\"id\", \"createTimeStamp\", \"updateTimeStamp\", \"content\", \"isSend\", \"phoneNo\", ",
        "\"desc\"",
        "from \"phone_message\"",
        "where \"id\" = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="content", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="isSend", javaType=Boolean.class, jdbcType=JdbcType.BIT),
        @Arg(column="phoneNo", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="desc", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    PhoneMessage selectByPrimaryKey(Long id);
}