package com.foo.tourist.dao;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;
import org.louis.hometutor.po.PhoneLog;
import org.louis.hometutor.po.PhoneLogExample;

public interface PhoneLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_log
     *
     * @mbggenerated
     */
    @SelectProvider(type=PhoneLogSqlProvider.class, method="countByExample")
    int countByExample(PhoneLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_log
     *
     * @mbggenerated
     */
    @SelectProvider(type=PhoneLogSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="callingPhoneNo", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="calledPhoneNo", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="beginTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="endTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="isSuccess", javaType=Boolean.class, jdbcType=JdbcType.BIT),
        @Arg(column="failReason", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="recordUrl", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="sessionId", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="fromObjectId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="fromObjectType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="callReason", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="toObjectId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="toObjectType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="status", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<PhoneLog> selectByExample(PhoneLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_log
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "\"id\", \"createTimeStamp\", \"updateTimeStamp\", \"callingPhoneNo\", \"calledPhoneNo\", ",
        "\"beginTimeStamp\", \"endTimeStamp\", \"isSuccess\", \"failReason\", \"recordUrl\", ",
        "\"sessionId\", \"fromObjectId\", \"fromObjectType\", \"callReason\", \"toObjectId\", ",
        "\"toObjectType\", \"status\"",
        "from \"phone_log\"",
        "where \"id\" = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="callingPhoneNo", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="calledPhoneNo", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="beginTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="endTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="isSuccess", javaType=Boolean.class, jdbcType=JdbcType.BIT),
        @Arg(column="failReason", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="recordUrl", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="sessionId", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="fromObjectId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="fromObjectType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="callReason", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="toObjectId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="toObjectType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="status", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    PhoneLog selectByPrimaryKey(Long id);
}