package com.foo.tourist.dao;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;
import org.louis.hometutor.po.PushMessage;
import org.louis.hometutor.po.PushMessageExample;

public interface PushMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_message
     *
     * @mbggenerated
     */
    @SelectProvider(type=PushMessageSqlProvider.class, method="countByExample")
    int countByExample(PushMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_message
     *
     * @mbggenerated
     */
    @SelectProvider(type=PushMessageSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="receiverId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="receiverType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="deviceInfo", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="pushToken", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="content", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="isSend", javaType=Boolean.class, jdbcType=JdbcType.BIT),
        @Arg(column="url", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<PushMessage> selectByExample(PushMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_message
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "\"id\", \"createTimeStamp\", \"updateTimeStamp\", \"receiverId\", \"receiverType\", ",
        "\"deviceInfo\", \"pushToken\", \"content\", \"isSend\", \"url\"",
        "from \"push_message\"",
        "where \"id\" = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="receiverId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="receiverType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="deviceInfo", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="pushToken", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="content", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="isSend", javaType=Boolean.class, jdbcType=JdbcType.BIT),
        @Arg(column="url", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    PushMessage selectByPrimaryKey(Long id);
}