package com.foo.tourist.dao;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;
import org.louis.hometutor.po.RoleAuth;
import org.louis.hometutor.po.RoleAuthExample;

public interface RoleAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_auth
     *
     * @mbggenerated
     */
    @SelectProvider(type=RoleAuthSqlProvider.class, method="countByExample")
    int countByExample(RoleAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_auth
     *
     * @mbggenerated
     */
    @SelectProvider(type=RoleAuthSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="roleId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="authId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="isdel", javaType=Boolean.class, jdbcType=JdbcType.BIT),
        @Arg(column="updatorId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="creatorId", javaType=Long.class, jdbcType=JdbcType.BIGINT)
    })
    List<RoleAuth> selectByExample(RoleAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_auth
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "\"id\", \"createTimeStamp\", \"updateTimeStamp\", \"roleId\", \"authId\", \"isdel\", ",
        "\"updatorId\", \"creatorId\"",
        "from \"role_auth\"",
        "where \"id\" = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="roleId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="authId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="isdel", javaType=Boolean.class, jdbcType=JdbcType.BIT),
        @Arg(column="updatorId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="creatorId", javaType=Long.class, jdbcType=JdbcType.BIGINT)
    })
    RoleAuth selectByPrimaryKey(Long id);
}