package com.foo.tourist.dao;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;
import org.louis.hometutor.po.TopicFreeConsultContent;
import org.louis.hometutor.po.TopicFreeConsultContentExample;

public interface TopicFreeConsultContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_free_consult_content
     *
     * @mbggenerated
     */
    @SelectProvider(type=TopicFreeConsultContentSqlProvider.class, method="countByExample")
    int countByExample(TopicFreeConsultContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_free_consult_content
     *
     * @mbggenerated
     */
    @SelectProvider(type=TopicFreeConsultContentSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="topicId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="creatorId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="creatorType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="updatorId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="updatorType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="diseaseDesc", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="treatmentHistory", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="answerId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="answerType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="answerName", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="replyStatus", javaType=Integer.class, jdbcType=JdbcType.INTEGER)
    })
    List<TopicFreeConsultContent> selectByExample(TopicFreeConsultContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_free_consult_content
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "\"id\", \"topicId\", \"createTimeStamp\", \"updateTimeStamp\", \"creatorId\", ",
        "\"creatorType\", \"updatorId\", \"updatorType\", \"diseaseDesc\", \"treatmentHistory\", ",
        "\"answerId\", \"answerType\", \"answerName\", \"replyStatus\"",
        "from \"topic_free_consult_content\"",
        "where \"id\" = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="topicId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="creatorId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="creatorType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="updatorId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="updatorType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="diseaseDesc", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="treatmentHistory", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="answerId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="answerType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="answerName", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="replyStatus", javaType=Integer.class, jdbcType=JdbcType.INTEGER)
    })
    TopicFreeConsultContent selectByPrimaryKey(Long id);
}