package com.foo.tourist.dao;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;
import org.louis.hometutor.po.TopicFreeConsultResource;
import org.louis.hometutor.po.TopicFreeConsultResourceExample;

public interface TopicFreeConsultResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_free_consult_resource
     *
     * @mbggenerated
     */
    @SelectProvider(type=TopicFreeConsultResourceSqlProvider.class, method="countByExample")
    int countByExample(TopicFreeConsultResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_free_consult_resource
     *
     * @mbggenerated
     */
    @SelectProvider(type=TopicFreeConsultResourceSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="topicId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="resourceUrl", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<TopicFreeConsultResource> selectByExample(TopicFreeConsultResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_free_consult_resource
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "\"id\", \"createTimeStamp\", \"topicId\", \"resourceUrl\"",
        "from \"topic_free_consult_resource\"",
        "where \"id\" = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="topicId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="resourceUrl", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    TopicFreeConsultResource selectByPrimaryKey(Long id);
}