package com.foo.tourist.dao;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;
import org.louis.hometutor.po.TopicLockLog;
import org.louis.hometutor.po.TopicLockLogExample;

public interface TopicLockLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_lock_log
     *
     * @mbggenerated
     */
    @SelectProvider(type=TopicLockLogSqlProvider.class, method="countByExample")
    int countByExample(TopicLockLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_lock_log
     *
     * @mbggenerated
     */
    @SelectProvider(type=TopicLockLogSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="userId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="userType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="lockReason", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<TopicLockLog> selectByExample(TopicLockLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_lock_log
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "\"id\", \"createTimeStamp\", \"userId\", \"userType\", \"lockReason\"",
        "from \"topic_lock_log\"",
        "where \"id\" = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="userId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="userType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="lockReason", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    TopicLockLog selectByPrimaryKey(Long id);
}