package com.foo.tourist.dao;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;
import org.louis.hometutor.po.UnVerifyArticleResource;
import org.louis.hometutor.po.UnVerifyArticleResourceExample;

public interface UnVerifyArticleResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table un_verify_article_resource
     *
     * @mbggenerated
     */
    @SelectProvider(type=UnVerifyArticleResourceSqlProvider.class, method="countByExample")
    int countByExample(UnVerifyArticleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table un_verify_article_resource
     *
     * @mbggenerated
     */
    @SelectProvider(type=UnVerifyArticleResourceSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="resourceUrl", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="unVerifyArticleId", javaType=Long.class, jdbcType=JdbcType.BIGINT)
    })
    List<UnVerifyArticleResource> selectByExample(UnVerifyArticleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table un_verify_article_resource
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "\"id\", \"createTimeStamp\", \"updateTimeStamp\", \"resourceUrl\", \"unVerifyArticleId\"",
        "from \"un_verify_article_resource\"",
        "where \"id\" = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="resourceUrl", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="unVerifyArticleId", javaType=Long.class, jdbcType=JdbcType.BIGINT)
    })
    UnVerifyArticleResource selectByPrimaryKey(Long id);
}