package com.foo.tourist.dao;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;
import org.louis.hometutor.po.UnVerifyArticle;
import org.louis.hometutor.po.UnVerifyArticleExample;

public interface UnVerifyArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table un_verify_article
     *
     * @mbggenerated
     */
    @SelectProvider(type=UnVerifyArticleSqlProvider.class, method="countByExample")
    int countByExample(UnVerifyArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table un_verify_article
     *
     * @mbggenerated
     */
    @SelectProvider(type=UnVerifyArticleSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="picUrl", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="title", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="content", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="creatorId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="creatorType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="status", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="type", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="reviewer", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="reviewerId", javaType=Long.class, jdbcType=JdbcType.BIGINT)
    })
    List<UnVerifyArticle> selectByExample(UnVerifyArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table un_verify_article
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "\"id\", \"createTimeStamp\", \"updateTimeStamp\", \"picUrl\", \"title\", \"content\", ",
        "\"creatorId\", \"creatorType\", \"status\", \"type\", \"reviewer\", \"reviewerId\"",
        "from \"un_verify_article\"",
        "where \"id\" = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="createTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="updateTimeStamp", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="picUrl", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="title", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="content", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="creatorId", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="creatorType", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="status", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="type", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="reviewer", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="reviewerId", javaType=Long.class, jdbcType=JdbcType.BIGINT)
    })
    UnVerifyArticle selectByPrimaryKey(Long id);
}